### ISSUE TITLE
Visualizzazione degli orari

### ISSUE THREAD

**Issue by ghost** [Fast0n/Mediterraneabus#1]
Mediterraneabus 0.1
Android 5.1
Build Flyme 6.3.0.0G
Meizu M3 Note

<a><img src='https://user-images.githubusercontent.com/5260133/39663379-b7338a56-5072-11e8-93ef-d2ba4b16c10a.jpg' height='400' alt='icon'/></a>

Problema grafico
Problema con la generazione degli orari

**Comment by Fast0n** [comment]
Close issues via commit 60313d4
